# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'gksruf'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: Featured Projects
    submenu:
      - name: 
        link: 
      - name: 
        link: 
  - name: Posts
    link: /posts
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/gksruf2
      - name: LinkedIn
        icon: linkedin-square
        link: 
      - name: Twitter
        icon: twitter
        link: 
    
